# Problem Statement: https://www.hackerearth.com/challenges/competitive/may-circuits-20/algorithm/or-b3c038d1/
'''
how many distinct numbers can be generated by doing bitwise OR of one or more integers between A and B (inclusive)?
'''
